package dev.cannoli.igm

enum class CanonicalButton {
    BTN_UP, BTN_DOWN, BTN_LEFT, BTN_RIGHT,
    BTN_NORTH, BTN_SOUTH, BTN_EAST, BTN_WEST,
    BTN_L, BTN_L2, BTN_R, BTN_R2, BTN_L3, BTN_R3,
    BTN_LSTICK_X, BTN_LSTICK_Y, BTN_RSTICK_X, BTN_RSTICK_Y,
    BTN_START, BTN_SELECT, BTN_MENU,
}
