package dev.cannoli.scorza.ui.components

// Generated by scripts/sync_credits.py from credits.json. Do not edit by hand.

data class CreditEntry(val name: String, val detail: String)

data class LocalizationCredit(val languageTag: String, val contributors: List<String>)

val CREDITS_INSPIRATION: List<CreditEntry> = listOf(
    CreditEntry("Hallie", "My beautiful wife who makes me better in every way"),
    CreditEntry("Shaun Inman", "MinUI"),
    CreditEntry("Abraham McCampbell", "Cannoli Logo"),
)

val CREDITS_CORES: List<CreditEntry> = listOf(
    CreditEntry("Gambatte", "GPLv2"),
    CreditEntry("Genesis Plus GX", "Non-commercial"),
    CreditEntry("Handy", "Zlib"),
    CreditEntry("Mednafen NGP", "GPLv2"),
    CreditEntry("Mednafen PCE FAST", "GPLv2"),
    CreditEntry("Mednafen VB", "GPLv2"),
    CreditEntry("Mednafen WonderSwan", "GPLv2"),
    CreditEntry("mGBA", "MPLv2.0"),
    CreditEntry("Nestopia", "GPLv2"),
    CreditEntry("PCSX ReARMed", "GPLv2"),
    CreditEntry("PokeMini", "GPLv3"),
    CreditEntry("ProSystem", "GPLv2"),
    CreditEntry("Snes9x", "Non-commercial"),
    CreditEntry("Stella", "GPLv2"),
    CreditEntry("SwanStation", "GPLv3"),
)

val CREDITS_SHADERS: List<CreditEntry> = listOf(
    CreditEntry("crt-aperture by EasyMode", "GPL"),
    CreditEntry("crt-cannoli by Cannoli (based on EasyMode)", "GPL"),
    CreditEntry("crt-easymode by EasyMode", "GPL"),
    CreditEntry("crt-geom by cgwg / Themaister / DOLLS", "GPLv2"),
    CreditEntry("crt-lottes-fast by Timothy Lottes / hunterk", "Public domain"),
    CreditEntry("dot by Themaister", "Public domain"),
    CreditEntry("lcd3x by Gigaherz", "Public domain"),
    CreditEntry("scanline by hunterk", "Public domain"),
    CreditEntry("sharp-bilinear-simple by rsn8887", "Public domain"),
    CreditEntry("zfast-crt by SoltanGris42", "GPLv2"),
    CreditEntry("zfast-lcd by SoltanGris42", "GPLv2"),
)

val CREDITS_FONTS: List<CreditEntry> = listOf(
    CreditEntry("M+ Fonts Project", "OFL"),
    CreditEntry("BPreplay", "OFL"),
    CreditEntry("Nerd Fonts", "OFL"),
)

val CREDITS_LIBRARIES: List<CreditEntry> = listOf(
    CreditEntry("Apache Commons Compress", "Apache 2.0"),
    CreditEntry("PdfiumAndroid (io.legere)", "Apache 2.0"),
    CreditEntry("XZ for Java", "Public domain"),
    CreditEntry("ZXing", "Apache 2.0"),
)

val CREDITS_LOCALIZATION: List<LocalizationCredit> = listOf(
    LocalizationCredit("zh-CN", listOf("Bobby Chiang")),
    LocalizationCredit("fr-FR", listOf("Christophe Coquelet", "Dominic Drolet")),
    LocalizationCredit("de-DE", listOf("frysee")),
    LocalizationCredit("pt-PT", listOf("Christian Paolo Ramos")),
    LocalizationCredit("es-ES", listOf("Luke Nance", "Raadon", "ramsay nieve")),
    LocalizationCredit("uk-UA", listOf("MeEdytor")),
)
