#!/usr/bin/env python3
"""Generate the settings-screen table the IGM descends through, from RetroArch's own source.

Cannoli's All Settings defers to RetroArch for which rows exist, what they are called, how they are
grouped and in what order. Getting that means building a specific displaylist per screen, which
needs the screen's DISPLAYLIST_* constant. RetroArch knows it, but only through four static tables
across two files, none of them exported:

  MENU_ENUM_LABEL_VIDEO_SETTINGS                  ok_dl_map[]            menu_cbs_ok.c
    -> ACTION_OK_DL_VIDEO_SETTINGS_LIST           action_ok_dl_to_enum   menu_cbs_ok.c
    -> MENU_ENUM_LABEL_DEFERRED_VIDEO_SETTINGS..  deferred push table    menu_cbs_deferred_push.c
    -> deferred_push_video_settings_list          GENERIC_DEFERRED_PUSH  menu_cbs_deferred_push.c
    -> DISPLAYLIST_VIDEO_SETTINGS_LIST

Walking those four here and emitting the composed result keeps the mapping RetroArch's rather than
ours: a bump regenerates it, and a chain that breaks shows up as a missing row rather than a screen
that silently stops opening.
"""
import pathlib
import re
import sys

RA = pathlib.Path(__file__).resolve().parent.parent / "retroarch"


def read(rel):
    return (RA / rel).read_text(errors="replace")


# MENU_ENUM_LABEL_X -> "x", the label string a displaylist row carries.
def enum_to_label():
    out = {}
    text = read("msg_hash_lbl_str.h")
    for m in re.finditer(r'#define\s+MENU_ENUM_LABEL_(\w+?)_STR\s+"([^"]*)"', text):
        out["MENU_ENUM_LABEL_" + m.group(1)] = m.group(2)
    return out


# DISPLAYLIST_* -> the stack of cpp directives open at its line in the enum. Several are compiled
# out on Android, and naming one that is absent makes the whole generated table a syntax error.
def displaylist_guards():
    text = read("menu/menu_displaylist.h")
    body = re.search(r'enum menu_displaylist_ctl_state\s*\{(.*?)\n\};', text, re.S)
    if not body:
        return {}
    out, stack = {}, []
    for line in body.group(1).split("\n"):
        t = line.strip()
        if re.match(r'#\s*if(n?def)?\b', t):
            stack.append(re.sub(r'^#\s*', '', t))
        elif re.match(r'#\s*endif\b', t) and stack:
            stack.pop()
        elif re.match(r'#\s*el(se|if)\b', t) and stack:
            stack[-1] = "if !(" + re.sub(r'^#\s*el(se|if)\s*', '', stack[-1]) + ")"
        m = re.match(r'(DISPLAYLIST_\w+)\s*,', t)
        if m:
            out[m.group(1)] = list(stack)
    return out


def main():
    ok = read("menu/cbs/menu_cbs_ok.c")
    deferred = read("menu/cbs/menu_cbs_deferred_push.c")

    # 1. ok_dl_map[]: { MENU_ENUM_LABEL_VIDEO_SETTINGS, ACTION_OK_DL_VIDEO_SETTINGS_LIST },
    enum_to_action = {}
    table = re.search(r'static const ok_dl_map_t ok_dl_map\[\]\s*=\s*\{(.*?)\n\};', ok, re.S)
    if table:
        for m in re.finditer(r'\{\s*(MENU_ENUM_LABEL_\w+)\s*,\s*(ACTION_OK_DL_\w+)\s*\}', table.group(1)):
            enum_to_action.setdefault(m.group(1), m.group(2))

    # 2. action_ok_dl_to_enum(): case ACTION_OK_DL_X: return MENU_ENUM_LABEL_DEFERRED_X;
    action_to_deferred = {}
    fn = re.search(r'static enum msg_hash_enums action_ok_dl_to_enum\(.*?\n\}', ok, re.S)
    if fn:
        for m in re.finditer(r'case\s+(ACTION_OK_DL_\w+):\s*return\s+(MENU_ENUM_LABEL_\w+);', fn.group(0)):
            action_to_deferred.setdefault(m.group(1), m.group(2))

    # 3. The deferred push table: {MENU_ENUM_LABEL_DEFERRED_X, deferred_push_x},
    deferred_to_fn = {}
    for m in re.finditer(r'\{\s*(MENU_ENUM_LABEL_DEFERRED_\w+)\s*,\s*(deferred_push_\w+)\s*\}', deferred):
        deferred_to_fn.setdefault(m.group(1), m.group(2))

    # 4. GENERIC_DEFERRED_PUSH(deferred_push_x, DISPLAYLIST_X_LIST)
    fn_to_dl = {}
    for m in re.finditer(r'GENERIC_DEFERRED_PUSH\(\s*(\w+)\s*,\s*(DISPLAYLIST_\w+)\s*\)', deferred):
        fn_to_dl.setdefault(m.group(1), m.group(2))

    labels = enum_to_label()
    guards = displaylist_guards()
    rows = []
    for enum_idx, action in sorted(enum_to_action.items()):
        dl = fn_to_dl.get(deferred_to_fn.get(action_to_deferred.get(action, ""), ""), "")
        label = labels.get(enum_idx)
        # A chain that does not reach a plain displaylist is a screen the IGM cannot build: a
        # dropdown, a file browser, a list needing arguments we do not have. Those are dropped
        # rather than emitted broken, and the row simply does not open.
        # A constant this build does not declare cannot be named at all, so the row carries the
        # same guard the enum gives it and disappears with it.
        if dl and label and dl in guards:
            rows.append((label, dl, guards[dl]))

    out = [
        "/* GENERATED by scripts/ra-menu-screens.py. Do not edit.",
        " * Settings-screen label to the displaylist that builds it, composed from RetroArch's own",
        " * four lookup tables so a bump regenerates rather than drifts. */",
        "",
        "static const struct { const char *label; int dl; } ricotta_menu_screens[] = {",
    ]
    for label, dl, guard in rows:
        for g in guard:
            out.append("#" + g)
        out.append('   { "%s", %s },' % (label, dl))
        for _ in guard:
            out.append("#endif")
    out.append("};")
    out.append("")

    body = "\n".join(out)
    dest = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else None
    if dest:
        dest.write_text(body)
        print(f"{len(rows)} screens -> {dest}")
    else:
        sys.stdout.write(body)


main()
