#!/usr/bin/env python3
"""Sync credits.json to CreditsData.kt, taskfile.yml, and release.yml."""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main():
    credits = json.loads((ROOT / "credits.json").read_text(encoding="utf-8"))
    sync_credits_data(credits)
    sync_taskfile(credits)
    sync_workflow(credits)
    print("Synced credits.json \u2192 CreditsData.kt, taskfile.yml, release.yml")


def kt_string(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
    return f'"{escaped}"'


def entry_list(name, entries):
    if not entries:
        return f"val {name}: List<CreditEntry> = emptyList()\n"
    body = "\n".join(
        f"    CreditEntry({kt_string(label)}, {kt_string(detail)})," for label, detail in entries
    )
    return f"val {name}: List<CreditEntry> = listOf(\n{body}\n)\n"


def sync_credits_data(credits):
    path = ROOT / "app/src/main/java/dev/cannoli/scorza/ui/components/CreditsData.kt"

    localization = "\n".join(
        "    LocalizationCredit({}, listOf({})),".format(
            kt_string(loc["language"]),
            ", ".join(kt_string(name) for name in loc["contributors"]),
        )
        for loc in credits["localization"]
    )

    text = (
        "package dev.cannoli.scorza.ui.components\n"
        "\n"
        "// Generated by scripts/sync_credits.py from credits.json. Do not edit by hand.\n"
        "\n"
        "data class CreditEntry(val name: String, val detail: String)\n"
        "\n"
        "data class LocalizationCredit(val languageTag: String, val contributors: List<String>)\n"
        "\n"
        + entry_list(
            "CREDITS_INSPIRATION",
            [(i["name"], i["detail"]) for i in credits["inspiration"]],
        )
        + "\n"
        + entry_list(
            "CREDITS_CORES",
            [(i["name"], i["license"]) for i in credits["cores"]],
        )
        + "\n"
        + entry_list(
            "CREDITS_SHADERS",
            [(f'{i["shader"]} by {i["name"]}', i["license"]) for i in credits["shaders"]],
        )
        + "\n"
        + entry_list(
            "CREDITS_FONTS",
            [(i["name"], i["license"]) for i in credits["fonts"]],
        )
        + "\n"
        + entry_list(
            "CREDITS_LIBRARIES",
            [(i["name"], i["license"]) for i in credits["libraries"]],
        )
        + "\n"
        f"val CREDITS_LOCALIZATION: List<LocalizationCredit> = listOf(\n{localization}\n)\n"
    )
    path.write_text(text, encoding="utf-8")

def sync_taskfile(credits):
    path = ROOT / "taskfile.yml"
    text = path.read_text(encoding="utf-8")

    ids = "\n".join(f"        - {c['id']}" for c in credits["cores"])

    def replace_cores(m):
        return m.group(1) + ids + "\n"

    text = re.sub(
        r'(      CORES:\n)(?:        - .*\n)+',
        replace_cores,
        text,
    )
    path.write_text(text, encoding="utf-8")


def sync_workflow(credits):
    path = ROOT / ".github/workflows/release.yml"
    text = path.read_text(encoding="utf-8")

    ids = [c["id"] for c in credits["cores"]]
    lines = []
    line = "   "
    for id_ in ids:
        if len(line) + 1 + len(id_) > 80:
            lines.append(line)
            line = "    " + id_
        else:
            line += " " + id_
    lines.append(line)
    block = "\n".join(lines)

    def replace_cores(m):
        return m.group(1) + block + "\n"

    text = re.sub(
        r'(  CORES: >-\n)(?:    .*\n)+',
        replace_cores,
        text,
    )
    path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
